config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :expenses
  resources :categories
  devise_scope :user do
    root to: "devise/sessions#new"
  end


  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  def index
    @expenses = Expense.where(user_id: current_user.id).order(:date).paginate(page: params[:page], per_page: 10)
    if params[:category].present? && (category = Category.find_by_id params[:category]).present?
      @expenses = @expenses.where category: category
    end
    if params[:from_date].present? && params[:to_date].present?
      from_date = extract_date params[:from_date]
      to_date = extract_date params[:to_date]
      @expenses = @expenses.where 'date between ? and ?', from_date, to_date
    else
      @expenses = @expenses.where 'date between ? and ?', Date.today.beginning_of_month, Date.today.end_of_month
    end
    @sum_all_expenses = @expenses.sum :value
  end

  def new
    @expense = Expense.new
  end

  def edit
    @expense = Expense.find params[:id]
  end

  def create
    expense = Expense.new expense_params
    expense.user_id = current_user.id
    if expense.save
      redirect_to expenses_path
    else
      @expense = expense
      render 'new'
    end
  end

  def update
    expense = Expense.find params[:id]
    if expense.update expense_params
      redirect_to expenses_path
    else
      @expense = expense
      render 'edit'
    end
  end

  def destroy
    expense = Expense.find params[:id]
    expense.destroy
    redirect_to expenses_path
  end

  private

  def extract_date(date)
    date_result = date['(1i)'] + '-' + date['(2i)'] + '-' + date['(3i)']
    date_result.to_date
  end

  def expense_params
    params.require(:expense).permit(:name, :value, :date, :category_id)
  end

end

app/helpers/expenses_helper.rb
module ExpensesHelper
  def sum_expenses_value
    sum = 0
    @expenses.all.each do |expense|
      sum += expense.value
    end
    sum
  end

  def categories_options
    options = Category.where(user_id: current_user.id).collect {|c| [c.name, c.id]}
    options.unshift ["All", 0]
    options
  end

  def user_categories
    Category.where(user_id: current_user.id)
  end
end

app/views/expenses/_expenses_list.html.erb
<div class="digg_pagination">
  <%= will_paginate @expenses,:previous_label => t('will_paginate.previous'), :next_label => t('will_paginate.next') %>
</div>
<table class="table table-bordered table-striped table-condensed table-hover table-responsive">
  <tr class="shown">
    <th><%= t('name') %></th>
    <th><%= t('value') %></th>
    <th><%= t('date_head') %></th>
    <th><%= t('category') %></th>
  </tr>
  <% @expenses.each do |expense| %>
    <tr>
      <td><%= expense.name %></td>
      <td><%= expense.value %></td>
      <td><%= expense.date %></td>
      <td><%= expense.category.name %></td>
      <td><%= link_to t('edit'), edit_expense_path(expense) %></td>
      <td><%= link_to t('delete'), expense, method: :delete, data: {confirm: t('are_you_sure')} %></td>
    </tr>
  <% end %>
</table>
<div class="digg_pagination">
  <%= will_paginate @expenses,:previous_label => t('will_paginate.previous'), :next_label => t('will_paginate.next') %>
</div>
<br>
<h4><b><%= t('total_page') %>: </b> <%= sum_expenses_value %></h4>
<br>
<h4><b><%= t('total_all') %>: </b> <%= @sum_all_expenses %></h4>

app/views/expenses/_form.html.erb
<%= form_for @expense do |f| %>
  <ul>
    <% @expense.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <div>
    <%= f.label :name, :class => "control-label" %>
    <%= f.text_field :name %>
  </div>
  </br>
  <div>
    <%= f.label :value, :class => "control-label" %>
    <%= f.number_field :value, step: :any %>
  </div>
  </br>
  <div>
    <%= f.label :date, :class => "control-label" %>
    <%= f.date_select :date %>
  </div>
  </br>
  <div>
    <%= f.label :category, :class => "control-label" %>
    <%= f.select :category_id, user_categories.collect {|c| [c.name, c.id]}, {include_blank: true} %>
  </div>
  </br>
  <div>
    <%= f.submit t('submit_expense'), class: "btn btn-primary" %>
  </div>

<% end %>

app/views/expenses/edit.html.erb
<h1><%= t('edit_expense') %>Edit Expense</h1>
<%= render 'form' %>

app/views/expenses/index.html.erb
<%= link_to t('new_expense'), new_expense_path, class: "btn btn-primary pull-right", style: 'margin: 10px' %>
<%= link_to t('new_category'), new_category_path, class: "btn btn-primary pull-right", style: 'margin: 10px' %>
<%= link_to t('categories'), categories_path, class: "btn btn-primary pull-right", style: 'margin: 10px' %>


<%= form_tag({:action => 'index'}, {remote: true, :role => 'form', :method => :get, :class => 'form-inline',:style => 'margin-left: 15px', :id => 'filter-expenses'}) do %>

  <div class="row" style="margin-right: 30px">
    <%= label_tag t('category') %>
    <%= select_tag :category, options_for_select(categories_options), {allow_blank: true} %>
  </div>

  <div class="row">
    <%= label_tag t('from_date') %>
    <%= date_select :from_date, nil, selected: Date.today.beginning_of_month %>
  </div>

  <div class="row mt">
    <%= label_tag t('to_date') %>
    <%= date_select :to_date, nil, selected: Date.today.end_of_month %>
  </div>

  <div class="row mt">
    <%= button_tag t('filter'), type: 'submit', class: 'btn btn-default' %>
  </div>
<% end %>


</br>
<div id="expenses-list">
  <%= render 'expenses_list' %>
</div>

app/views/expenses/index.js.erb
$("#expenses-list").html("<%= escape_javascript(render('expenses_list')) %>");
// $(".overlay").fadeOut()

app/views/expenses/new.html.erb
<div align="center">
  <h1><%= t('new_expense') %></h1>
  <%= render 'form' %>
</div>